server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/productcommunitydb
spring.datasource.username=root
spring.datasource.password=root

#Hibernate
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

#Hibernate auto ddl
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.format_sql = true
spring.security.user.password=Test12345_